#!/bin/bash

xcodebuild \
  -project CardsPlayin.xcodeproj \
  -scheme CardsPlayin \
  -sdk iphonesimulator \
  -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.1' \
  test \
  | xcbeautify
